version: '3.8'

services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    restart: always
    network_mode: "host"
  dev-server: 
    image: dev-server:latest
    container_name: dev-server
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    network_mode: "host"